export const buyers = [
  {
    id: 1,
    name: "John",
    averageCheck: Math.ceil(Math.random() * 500),
    purchases: Math.ceil(Math.random() * 100),
    totalRevenues: Math.ceil(Math.random() * 1000),
  },
  {
    id: 2,
    name: "Nancy",
    averageCheck: Math.ceil(Math.random() * 500),
    purchases: Math.ceil(Math.random() * 100),
    totalRevenues: Math.ceil(Math.random() * 1000),
  },
  {
    id: 3,
    name: "Sid",
    averageCheck: Math.ceil(Math.random() * 500),
    purchases: Math.ceil(Math.random() * 100),
    totalRevenues: Math.ceil(Math.random() * 1000),
  },
  {
    id: 4,
    name: "John",
    averageCheck: Math.ceil(Math.random() * 500),
    purchases: Math.ceil(Math.random() * 100),
    totalRevenues: Math.ceil(Math.random() * 1000),
  },
  {
    id: 5,
    name: "Tommy",
    averageCheck: Math.ceil(Math.random() * 500),
    purchases: Math.ceil(Math.random() * 100),
    totalRevenues: Math.ceil(Math.random() * 1000),
  },
  {
    id: 6,
    name: "Jack",
    averageCheck: Math.ceil(Math.random() * 500),
    purchases: Math.ceil(Math.random() * 100),
    totalRevenues: Math.ceil(Math.random() * 1000),
  },
  {
    id: 7,
    name: "Mary",
    averageCheck: Math.ceil(Math.random() * 500),
    purchases: Math.ceil(Math.random() * 100),
    totalRevenues: Math.ceil(Math.random() * 1000),
  },
  {
    id: 8,
    name: "Bill",
    averageCheck: Math.ceil(Math.random() * 500),
    purchases: Math.ceil(Math.random() * 100),
    totalRevenues: Math.ceil(Math.random() * 1000),
  },
  {
    id: 9,
    name: "Don",
    averageCheck: Math.ceil(Math.random() * 500),
    purchases: Math.ceil(Math.random() * 100),
    totalRevenues: Math.ceil(Math.random() * 1000),
  },
  {
    id: 10,
    name: "Marina",
    averageCheck: Math.ceil(Math.random() * 500),
    purchases: Math.ceil(Math.random() * 100),
    totalRevenues: Math.ceil(Math.random() * 1000),
  },
  {
    id: 11,
    name: "Vera",
    averageCheck: Math.ceil(Math.random() * 500),
    purchases: Math.ceil(Math.random() * 100),
    totalRevenues: Math.ceil(Math.random() * 1000),
  },
  {
    id: 12,
    name: "John",
    averageCheck: Math.ceil(Math.random() * 500),
    purchases: Math.ceil(Math.random() * 100),
    totalRevenues: Math.ceil(Math.random() * 1000),
  },
  {
    id: 13,
    name: "Pit",
    averageCheck: Math.ceil(Math.random() * 500),
    purchases: Math.ceil(Math.random() * 100),
    totalRevenues: Math.ceil(Math.random() * 1000),
  },
  {
    id: 14,
    name: "Angelina",
    averageCheck: Math.ceil(Math.random() * 500),
    purchases: Math.ceil(Math.random() * 100),
    totalRevenues: Math.ceil(Math.random() * 1000),
  },
  {
    id: 15,
    name: "Amy",
    averageCheck: Math.ceil(Math.random() * 500),
    purchases: Math.ceil(Math.random() * 100),
    totalRevenues: Math.ceil(Math.random() * 1000),
  },
];
